FROM python:3.9-slim

WORKDIR /

COPY ./requirements.txt /requirements.txt

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get update && apt-get install -y git-lfs

RUN ls
RUN git lfs fetch --all

RUN pip install --upgrade pip

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential && \
    pip install --no-cache-dir --upgrade -r /requirements.txt && \
    apt-get remove -y build-essential && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* /root/.cache

COPY . /

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]