name: NutriInsight-DB-Cassandra

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: cognispace # TODO: update Google Cloud project id
  GAR_LOCATION: europe-central2
  SERVICE: nutriInsightCassandra
  REGION: europe-central2

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Google Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build and Push Container
        run: |-
          gcloud auth list
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
          cd NutriInsight.API
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ github.sha }} dockerfile.cassandra
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ github.sha }}
